server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: container
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
            time: time
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # System logs (if available)
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog

  # Agenda API specific logs (JSON structured)
  - job_name: agenda-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: agenda-api
          service: agenda-api
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            container_name: attrs.tag
            timestamp: time
      - regex:
          expression: 'agenda-api'
          source: container_name
      - match:
          selector: '{job="agenda-api"}'
          stages:
          - json:
              expressions:
                level: level
                message: message
                event: event
                method: method
                status_code: status_code
              source: output
          - labels:
              level:
              event:
              method:
              status_code: